EV-968 - 01 Back end criação do usuário
And-Martins/accelerate-everest-dotnet-api pull request #1
Opened 2022-11-18 18:09 UTC by andre-pereira-martins

[Link do card no Jira](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-968)

- [x] CRUD feito
- [x] Dados salvos na memória através de lista privada
- [x] Projeto separado da Main
- [x] Retornos corretos dos endpoints
- [x] Verificando os campos de cpf e e-mail

2022-11-18 18:35 UTC, santosclaudinei-warren commented on CustomerRegister/Controllers/CustomerController.cs
> +        private readonly ICustomerService _customer;
```suggestion
        private readonly ICustomerService _customerService;
```

2022-11-18 18:37 UTC, santosclaudinei-warren commented on CustomerRegister/Controllers/CustomerController.cs
> +            }
Evitar lógicas/ regras de negócio na controller. Fazer isso na CustomerService

2022-11-18 18:39 UTC, santosclaudinei-warren commented on CustomerRegister/Repositories/CustomerService.cs
> +        public bool AddCustomer(CustomerEntity customer)
```suggestion
        public int AddCustomer(CustomerEntity customer)
```
Já que você optou por configurar um tipo no retorno. Deveria retornar o id do customer criado.

2022-11-18 18:42 UTC, santosclaudinei-warren commented on CustomerRegister/Models/CustomerEntity.cs
> +            int addressNumber)
```suggestion
        public CustomerEntity(
            string fullName,
            string email, 
            string emailConfirmation, 
            string cpf, 
            string cellphone,
            DateTime dataOfBirth,
            bool emailSms,
            bool whatsapp,
            string country,
            string city,
            string postalCode,
            string address,
            int addressNumber
        )
```

2022-11-18 18:43 UTC, santosclaudinei-warren commented on CustomerRegister/Models/CustomerEntity.cs
> +﻿
```suggestion
```

2022-11-18 18:43 UTC, santosclaudinei-warren commented on CustomerRegister/Models/CustomerEntity.cs
> +
```suggestion
```

2022-11-18 18:44 UTC, santosclaudinei-warren commented on CustomerRegister/Program.cs
> +
```suggestion
```

2022-11-18 18:45 UTC, DevClaudinei commented on CustomerRegister/Repositories/CustomerService.cs
> +
```suggestion
```

2022-11-18 18:45 UTC, santosclaudinei-warren commented on CustomerRegister/Repositories/CustomerService.cs
> +
```suggestion
```

2022-11-18 18:49 UTC, santosclaudinei-warren commented on CustomerRegister/Repositories/CustomerService.cs
> +            var response = _customers.Any(customer => customer.Cpf == selectedCustomer.Cpf || customer.Email == selectedCustomer.Email) && (selectedCustomer.Id != selectedCustomer.Id);
```suggestion
            var response = _customers
                .Any(customer => customer.Cpf == selectedCustomer.Cpf || customer.Email == selectedCustomer.Email) && (selectedCustomer.Id != selectedCustomer.Id);
```
Para ficar visível todo o código, eu faria assim.

2022-11-18 18:52 UTC, santosclaudinei-warren commented on CustomerRegister/Repositories/CustomerService.cs
> +            return false;
```suggestion
            if(_customers.Any(customer => customer.Cpf == selectedCustomer.Cpf || customer.Email == selectedCustomer.Email))
                return true;

            return false;
```
Pode ser feito como sugerido acima. Entretanto, eu faria um If para lidar com cpf ja existente e outro para email.

2022-11-18 18:54 UTC, santosclaudinei-warren commented on CustomerRegister/Repositories/CustomerService.cs
> +            return true;
```suggestion
            customer.Id = _customers.LastOrDefault()?.Id + 1 ?? 1;

            if (Exists(customer)) return false;

            if(DuplicatedRegister(customer)) return false;

            _customers.Add(customer);
            return true;
```
Separação do código para ficar mais visível.

2022-11-18 18:55 UTC, santosclaudinei-warren commented on CustomerRegister/Repositories/CustomerService.cs
> +            return true;
```suggestion
            int index = _customers.FindIndex(customer => customer.Id == id);

            if(index == -1) return false;

            _customers.RemoveAt(index);
            return true;
```

2022-11-18 19:01 UTC, santosclaudinei-warren commented on CustomerRegister/Controllers/CustomerController.cs
> +
```suggestion
```

2022-11-18 19:02 UTC, santosclaudinei-warren commented on CustomerRegister/Controllers/CustomerController.cs
> +
```suggestion
```

2022-11-18 19:06 UTC, santosclaudinei-warren commented on CustomerRegister/CustomerRegister.csproj
> +	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.2.0" />
Corrigir indentação.

2022-11-18 19:07 UTC, santosclaudinei-warren commented on CustomerRegister/CustomerRegister.csproj
> +      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
```suggestion
```
Pacotes não serão utilizados.

2022-11-21 12:19 UTC, andre-pereira-martins commented on CustomerRegister/Repositories/CustomerService.cs
> +        public bool AddCustomer(CustomerEntity customer)
Feito

2022-11-21 13:21 UTC, AndreMartinsWarren commented on CustomerRegister/Controllers/CustomerController.cs
> +            }
feito

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Controllers/CustomerController.cs
> +                : BadRequest("Email ou CPF já exitem");
Tenta deixar essas verificações pra camada de service com as exceções, o ideal é ter o mínimo possível de lógica na controller

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Controllers/CustomerController.cs
> +                : Ok(response);
Mesmo caso acima

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Controllers/CustomerController.cs
> +                : NotFound($"O usuário com id: {id} não foi encontrado");
Mesmo caso acima

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Controllers/CustomerController.cs
> +        public IActionResult SearchAllCustomers()
```suggestion
        public IActionResult GetAllCustomers()
```

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Controllers/CustomerController.cs
> +        public IActionResult SearchCustomerById(int id)
```suggestion
        public IActionResult GetCustomerById(int id)
```

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Repositories/CustomerService.cs
> +        public CustomerEntity SearchCustomerById(int id)
```suggestion
        public CustomerEntity GetCustomerById(int id)
```

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Repositories/CustomerService.cs
> +        public List<CustomerEntity> SearchAllCustomers()
```suggestion
        public List<CustomerEntity> GetAllCustomers()
```

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Repositories/CustomerService.cs
> +        public bool DeleteCustomer(int id)
Você já tá na service de customer, acho que não faz sentido adicionar customer junto dos nomes dos métodos
```suggestion
        public bool Delete(int id)
```

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Repositories/CustomerService.cs
> +        public void UpdateCustomer (CustomerEntity selectedCustomer, int id)
Mesmo caso acima

2022-11-21 13:34 UTC, LuanFortunatoW commented on CustomerRegister/Repositories/CustomerService.cs
> +        public int AddCustomer(CustomerEntity customer)
Mesmo caso acima

2022-11-21 14:19 UTC, andre-pereira-martins commented on CustomerRegister/CustomerRegister.csproj
> +	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.2.0" />
feito

2022-11-21 14:21 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +                : BadRequest("Email ou CPF já exitem");
feito

2022-11-21 14:21 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +                : Ok(response);
feito

2022-11-21 14:21 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +                : NotFound($"O usuário com id: {id} não foi encontrado");
feito

2022-11-21 14:24 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +        public IActionResult SearchAllCustomers()
feito

2022-11-21 14:25 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +        public IActionResult SearchCustomerById(int id)
feito

2022-11-21 14:26 UTC, andre-pereira-martins commented on CustomerRegister/Repositories/CustomerService.cs
> +        public CustomerEntity SearchCustomerById(int id)
feito

2022-11-21 14:26 UTC, andre-pereira-martins commented on CustomerRegister/Repositories/CustomerService.cs
> +        public List<CustomerEntity> SearchAllCustomers()
feito

2022-11-21 14:27 UTC, AndreMartinsWarren commented on CustomerRegister/Repositories/CustomerService.cs
> +        public bool DeleteCustomer(int id)
feito

2022-11-21 14:28 UTC, andre-pereira-martins commented on CustomerRegister/Repositories/CustomerService.cs
> +        public void UpdateCustomer (CustomerEntity selectedCustomer, int id)
feito

2022-11-21 14:28 UTC, andre-pereira-martins commented on CustomerRegister/Repositories/CustomerService.cs
> +        public int AddCustomer(CustomerEntity customer)
feito

2022-11-21 15:03 UTC, santosclaudinei-warren commented on CustomerRegister/Services/CustomerService.cs
> +        public void Update (CustomerEntity selectedCustomer, int id)
Rever a lógica do método, realizar checagens para retorno de erro mais assertivo. Ex: se o email já existe retornar essa mensagem de erro.

2022-11-21 15:03 UTC, santosclaudinei-warren commented on CustomerRegister/Services/CustomerService.cs
> +using BadRequestException = SendGrid.Helpers.Errors.Model.BadRequestException;
Verificar usings não utilizados / desnecessários

2022-11-21 15:04 UTC, santosclaudinei-warren commented on CustomerRegister/Controllers/CustomerController.cs
> +using System.Collections.Generic;
Verificar usings não utilizados / desnecessários.

2022-11-21 15:09 UTC, gregoryzimmerwarren requested changes
Deixei alguns comentários.

Qualquer dúvida estou a disposição.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister.sln
> +﻿
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +using System.Collections.Generic;
Da uma olhada nos teus usings para ver se todos estão sendo utilizados, tem o atalho Ctrl + R + G que exclui os não utilizados (mas tem que fazer em cada arquivo individualmente).

Recomendo ver isso em todos os arquivos.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +                : Ok(response);
Na controller não é interessante ter lógica. Então faz uso apenas do try catch aqui, e no teu Service você faz a lógica e lança as Exceptions.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +            return Ok(response);
Faz um try catch aqui, com um catch sem parâmetro que vai ter um return NoContent() dentro.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +        public IActionResult UpdateCustomer(CustomerEntity selectedCustomer, int id)
Como teu CustomerEntity é herança de BaseEntity ele já tem um Id, não? Assim, acredito que não é necessário passar o Id separadamente.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +        [HttpPut("{id}")]
```suggestion
        [HttpPut]
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerRegister.csproj
> +    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
```suggestion
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.1" /
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerRegister.csproj
> +    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
A princípio você só deveria estar usando estes packages.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +                NotNull().
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +                NotNull().
Não é necessário tento o NotEmpty()

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +                NotEqual("").
É o mesmo que NotEmpty, rever se é isso mesmo que você queria ou se era pra ser como no Cpf: NotEqual(" ").

Se for como está pode retirar em todos, se for como no do Cpf tem que corrigir em todos.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +                Length(11).
Dessa forma ele permite que o usuário digite algo além dos números?
Acredito ser mais interessante ter essa validação de tamanho apenas no métodos IsValidCpf após você fazer a correção da string retirando possíveis . , - e espaços.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +                Length(11).
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +
Entendo porque você colocou, pensando no Json, mas o usuário não vai de fato passar nesse formato para o back, então como são booleanos, não há a necessidade de uma validação, sempre vai haver um valor (true ou false).

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +            return Ok(response);
Coloca em um try catch também. Com o catch sem parâmetro e um return NoContet().

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +            if (cpf.Length != 11) return false;
```suggestion
            if (cpf.Length != 11)
               return false;
               
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +            }
```suggestion

            if (resto < 2)
                resto = 0;
            else
                resto = 11 - resto;
                
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +            }
Quanto if ou else tem apenas uma linha de comando interno não precisa colocar as { }

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +            }
```suggestion

            if (resto < 2)
                resto = 0;
            else
                resto = 11 - resto;
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Models/BaseEntity.cs
> +        public int Id { get; set; }
```suggestion
    public interface IEntity
    {
        int Id { get; set; }
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Models/CustomerEntity.cs
> +public class CustomerEntity : BaseEntity
```suggestion
public class CustomerEntity : IEntity
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Models/CustomerEntity.cs
> +public class CustomerEntity : BaseEntity
Implementar a interface

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Models/CustomerEntity.cs
> +            Cellphone = cellphone;
Seria interessante fazer um formatador para essas propriedades na forma de String Extension.

Por enquanto pode deixar salvo dentro dos teus models mesmo.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Models/CustomerEntity.cs
> +            PostalCode = postalCode;
Idem comentário anterior.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +        {
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +            // Add services to the container.
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +                .AddFluentValidation(x => x.RegisterValidatorsFromAssemblyContaining<CustomerValidations>());
```suggestion
            builder.Services.AddSingleton<ICustomerService, CustomerService>();
            builder.Services.AddFluentValidationAutoValidation();
            builder.Services.AddScoped<IValidator<CustomerEntity>, CustomerValidatons>
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +            // Configure the HTTP request pipeline.
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +}
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +        }
Acho mais interessante fazer as verificações de email e cpf separadas, pois assim tu consegue dar um erro mais assertivo para o usuário sobre o porque ele não conseguiu fazer tal ação.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +        public void Add(CustomerEntity customer)
```suggestion
        public void Create(CustomerEntity customer)
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +            }
Eu particularmente prefiro chamar o método GetCustomerById, uma vez que tu pede o id pro Delete.

Assim você reduz linhas e o erro da pesquisa já vem lá com teu Get. Aqui dai você usaria um Remove passando o customer que o Get te trouxe.

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +        public List<CustomerEntity> GetAllCustomers()
```suggestion
        public IEnumerable<CustomerEntity> GetAllCustomers()
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +            }
Esse erro já vem dentro do teu Get, e não faz muito sentido tua mensagem, afinal tu passou a pesquisa pelo Id, não pelo Cpf

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +            }
```suggestion
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +            }
Aqui você não está fazendo o contrário?

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +        public void Update (CustomerEntity selectedCustomer, int id)
```suggestion
        public void Update (CustomerEntity selectedCustomer)
```

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +        public void Update (CustomerEntity selectedCustomer, int id)
Já faz parte da tua entidade

2022-11-21 15:09 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/Interfaces/ICustomerService.cs
> +
```suggestion
        IEnumable<CustomerEntity> GetAllCustomers();
        CustomerEntity GetCustomerById(int id);
        void Add(CustomerEntity customer);
        void Update(CustomerEntity customer);
        void Delete(int id);
```

2022-11-21 15:13 UTC, viniciusoliveira-warren commented on CustomerRegister/Services/CustomerService.cs
> +        public void Add(CustomerEntity customer)
O termo mais correto aqui é Add mesmo pois apenas estamos salvando no banco, entidade já está criada

2022-11-21 15:16 UTC, viniciusoliveira-warren commented on CustomerRegister/Services/CustomerService.cs
> +        }
Em conjunto com o comentário do @gregoryzimmerwarren vale também adicionar uma mensagem de retorno referente o que não foi encontrado para retornarmos na api

2022-11-21 15:16 UTC, viniciusoliveira-warren commented on CustomerRegister/Services/CustomerService.cs
> +        public List<CustomerEntity> GetAllCustomers()
Não esquece de colocar a explicação do porquê deve ser feito a alteração

2022-11-21 16:07 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +                : Ok(response);
resolvido nos commits anteriores

2022-11-21 16:11 UTC, AndreMartinsWarren commented on CustomerRegister/Controllers/CustomerController.cs
> +using System.Collections.Generic;
feito

2022-11-21 16:11 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +using System.Collections.Generic;
feito

2022-11-21 16:11 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +using BadRequestException = SendGrid.Helpers.Errors.Model.BadRequestException;
feito

2022-11-21 16:14 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +        public IActionResult UpdateCustomer(CustomerEntity selectedCustomer, int id)
feito

2022-11-21 16:19 UTC, andre-pereira-martins commented on CustomerRegister/CustomerValidations.cs
> +                NotEqual("").
feito, mantido apenas os notEmpty

2022-11-21 16:20 UTC, andre-pereira-martins commented on CustomerRegister/CustomerValidations.cs
> +                Length(11).
feito

2022-11-21 16:21 UTC, andre-pereira-martins commented on CustomerRegister/CustomerValidations.cs
> +                Length(11).
feito

2022-11-21 16:26 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +        public List<CustomerEntity> GetAllCustomers()
@andre-pereira-martins basicamente pensa no que você quer fazer, se você está querendo retornar uma lista, apenas para visualizar os itens que estão contidos nela, utiliza o IEnumerable. Agora, se você quer fazer alterações nessa lista, ai você precisa que seja uma List, porque ela é uma classe que possui diversos métodos que te permitem essa manipulação.

2022-11-21 16:42 UTC, AndreMartinsWarren commented on CustomerRegister/Services/CustomerService.cs
> +        public void Add(CustomerEntity customer)
Manterei como Add

2022-11-21 18:00 UTC, AndreMartinsWarren commented on CustomerRegister/Program.cs
> +}
Feito

2022-11-21 18:11 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +            }
Feito

2022-11-21 18:18 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +            }
Feito

2022-11-21 18:37 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +            }
Corrigido

2022-11-21 18:38 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +        [HttpPut("{id}")]
Feito

2022-11-21 18:39 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +        }
Feito

2022-11-21 18:39 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +        public void Update (CustomerEntity selectedCustomer, int id)
Feito

2022-11-21 18:39 UTC, andre-pereira-martins commented on CustomerRegister/Services/Interfaces/ICustomerService.cs
> +
Feito

2022-11-21 18:40 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +        public void Update (CustomerEntity selectedCustomer, int id)
Feito

2022-11-21 18:45 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +            return Ok(response);
Feito

2022-11-21 18:48 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +            return Ok(response);
Feito

2022-11-21 18:50 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +            }
Feito

2022-11-21 18:56 UTC, andre-pereira-martins commented on CustomerRegister/CustomerRegister.csproj
> +    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
Feito

2022-11-21 19:34 UTC, andre-pereira-martins commented on CustomerRegister/Models/CustomerEntity.cs
> +            Cellphone = cellphone;
Feito

2022-11-21 19:34 UTC, andre-pereira-martins commented on CustomerRegister/Models/CustomerEntity.cs
> +            PostalCode = postalCode;
Feito

2022-11-21 19:58 UTC, gregoryzimmerwarren requested changes
Deixei novos comentários.

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +                return Created("", customer.Id);
```suggestion
                return Created("Id: ", customer.Id);
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +                return NotFound(e.Message);
```suggestion
                return BadRequest(e.Message);
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +                return Ok();
```suggestion
                return NoContent();
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +                return Ok();
Aqui é mais interessante que seja um NoContent(), resposta 204, porque não tem retorno nenhum desse endpoint.

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +                NotEqual("").
Os NotEqual(" ") e NotEqual("") ainda permaneceram. É pra ser assim mesmo?

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Models/IEntity.cs
> +    }
```suggestion
    public interface IEntity
    {
        int Id { get; set; }
    }
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Models/CustomerEntity.cs
> +public class CustomerEntity : IEntity
Precisa implementar a interface.

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +{
```suggestion
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +{
Rever a indentação

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +}
```suggestion
        app.Run();
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +
```suggestion
using System.Linq;
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +        }
Acredito ser melhor separar em dois para poder entregar uma mensagem mais assertiva sobre o que está duplicado, caso seja true a resposta, porque no método Create não tem nada seguindo essa possibilidade.

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +            _customers.Remove(GetCustomerById(id));
Aqui você está fazendo a chamada do GetCustomerById duas vezes, é mais interessante alocar em uma variável e dai usar ela para o Remove.

Você não precisa do if, porque o método Delete só vai ter continuação se o GetCustomerById não estourar a exeption.

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +                throw new ArgumentException($"Não foi encontrado usuário com Id : {id}");
```suggestion
                throw new ArgumentNullException($"Não foi encontrado usuário com Id : {id}");
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +                    _customers[index] = selectedCustomer;
Mesmo pensamento do Delete, você pode chamar o var index lá no começo, dai não precisa fazer o GetCustomerById  duas vezes.

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +        }
```suggestion
            }
        }
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +
Acredito que possam ser retirados.

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +            catch (ArgumentException e)
```suggestion
            catch (ArgumentNullException e)
```

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +            catch (ArgumentException e)
Vai ter outro catch para o ArgumentException

2022-11-21 19:58 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/Interfaces/ICustomerService.cs
> +
```suggestion
        void Delete(int id);
```

2022-11-21 20:04 UTC, andre-pereira-martins commented on CustomerRegister/CustomerValidations.cs
> +                NotEqual("").
Feito, as alterações haviam ficado em um commit que reverti quando ocorreu o problema com a IEntity

2022-11-21 20:08 UTC, andre-pereira-martins commented on CustomerRegister/Models/IEntity.cs
> +    }
Feito

2022-11-21 20:16 UTC, andre-pereira-martins commented on CustomerRegister/Models/CustomerEntity.cs
> +public class CustomerEntity : IEntity
Feito

2022-11-21 20:22 UTC, AndreMartinsWarren commented on CustomerRegister/Program.cs
> +}
deletado a linha em branco conforme conversado

2022-11-21 20:37 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +        }
como o e-mail e cpf já são comparados em funções separadas, mudei o nome dessa para ExistsID e agora ela só verifica se o ID existe

2022-11-21 20:39 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +            _customers.Remove(GetCustomerById(id));
Feito

2022-11-21 20:39 UTC, AndreMartinsWarren commented on CustomerRegister/Services/CustomerService.cs
> +                throw new ArgumentException($"Não foi encontrado usuário com Id : {id}");
alterado

2022-11-21 20:49 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +                    _customers[index] = selectedCustomer;
feito

2022-11-21 20:50 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +            catch (ArgumentException e)
feito

2022-11-22 01:07 UTC, santosclaudinei-warren commented on CustomerRegister/Services/CustomerService.cs
> +        }
Esses dois métodos são utilizados para verificar se um customer já existe. Você poderia criar um único e colocar os dois condicionai dentro deste. Assim, quando fosse criar ou atualizar, ele chamaria esse método e verificaria.
```suggestion
        private void CustomerAlreadyExists(CustomerEntity selectedCustomer)
        {
            if(_customers.Any(customer => customer.Email == selectedCustomer.Email))
                throw new ArgumentException("Este email já está em uso, por favor escolha outro");
                
            if (_customers.Any(customer => customer.Cpf == selectedCustomer.Cpf))
                throw new ArgumentException("Este CPF já está em uso, por favor escolha outro");
        }
```

2022-11-22 11:55 UTC, gregoryzimmerwarren requested changes
Verificar novos comentários.

Qualquer coisa estou a disposição.

2022-11-22 11:55 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +            }
```suggestion
            catch (ArgumentException e)
            {
                return BadRequest(e.Message);
            }
```

2022-11-22 11:55 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +            }
```suggestion
            } 
            catch
            {
                return NoContent();
            }
```

2022-11-22 11:55 UTC, gregoryzimmerwarren commented on CustomerRegister/Services/CustomerService.cs
> +                throw new ArgumentException($"Não foi encontrado usuário com Id : {id}");
```suggestion
                throw new ArgumentNullException($"Não foi encontrado usuário com Id : {id}");
```

2022-11-22 11:55 UTC, gregoryzimmerwarren commented on CustomerRegister/Controllers/CustomerController.cs
> +            }
No update tem mais um catch, o do ArgumentException das verificações de email e cpf

2022-11-22 11:55 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +                Length(11).
```suggestion
```

2022-11-22 11:55 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +                Length(11).
Essa validação é mais interessante de ser feita no métodos IsValidCpf. Mas antes de verificar se tem 11 caracteres faz a formatação com a string extension.

Se você faz a validação de tamanho aqui você tem que colocar tamanho 14, porque se não o usuário só poderia digitar, por exemplo, 111.111.111

2022-11-22 11:55 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +                NotEmpty();
Não acho necessário fazer validação de booleano. Sempre vai ser verdadeiro ou falso.

2022-11-22 11:55 UTC, gregoryzimmerwarren commented on CustomerRegister/Models/IEntity.cs
> +        public int Id { get; set; }
```suggestion
        int Id { get; set; }
```

2022-11-22 11:55 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +        app.Run();
Verificar a indentação com o atalho Ctrl + K + D

2022-11-22 12:00 UTC, andre-pereira-martins commented on CustomerRegister/CustomerValidations.cs
> +                NotEmpty();
retirado

2022-11-22 12:04 UTC, andre-pereira-martins commented on CustomerRegister/Program.cs
> +        app.Run();
Feito em todos os arquivos

2022-11-22 12:14 UTC, andre-pereira-martins commented on CustomerRegister/Controllers/CustomerController.cs
> +            }
feito

2022-11-22 12:22 UTC, gregoryzimmerwarren approved these changes
Deixei apenas mais um comentário. Mas já vou deixar aprovado, só implementar ali no método dai.

2022-11-22 12:22 UTC, gregoryzimmerwarren commented on CustomerRegister/CustomerValidations.cs
> +            if (cpf.All(x => x == cpf.First())) return false;
Aqui faltou implementar a verificação do tamanho máximo e o formatador do cpf.

2022-11-22 12:26 UTC, DevClaudinei commented on CustomerRegister/Services/CustomerService.cs
> +            customer.Id = _customers.LastOrDefault()?.Id + 1 ?? 1;
Essa linha garante que não irá se repetir um Id desde que você não informe um Id na criação do customer. Até porque no seu construtor não é necessário informar um Id, pois nessa linha ele percorre a lista e verifica os ids que já estão sendo utilizados.

2022-11-22 12:27 UTC, andre-pereira-martins commented on CustomerRegister/CustomerValidations.cs
> +            if (cpf.All(x => x == cpf.First())) return false;
feito

2022-11-22 12:28 UTC, santosclaudinei-warren commented on CustomerRegister/Services/CustomerService.cs
> +            customer.Id = _customers.LastOrDefault()?.Id + 1 ?? 1;
E informando um Id na requisição essa linha vai sobrescrever. O que torna a linha seguinte desnecessária.

2022-11-22 12:58 UTC, andre-pereira-martins commented on CustomerRegister/Services/CustomerService.cs
> +            customer.Id = _customers.LastOrDefault()?.Id + 1 ?? 1;
Feito

2022-11-22 13:58 UTC, LuanFortunatoW approved these changes

2022-11-22 15:37 UTC, santosclaudinei-warren approved these changes

2022-11-23 13:38 UTC, viniciusoliveira-warren commented on CustomerRegister/Controllers/CustomerController.cs
> +            }
Apenas devemos retornar 204 quando o endpoint não possui retorno o que nunca vai ser o caso aqui, como estamos fazendo GetAll ou vai retornar os dados ou uma lista vazia quando não tiver nenhum dado, ou seja, possui retorno.
```suggestion
            try
            {
                var listCustomers = _service.GetAll();
                return Ok(listCustomers);
            }
            catch (Exception ex)
            {
                var exMessage = ex.InnerException?.Message ?? ex.Message;
                return Problem(exMessage);
            }
```

2022-11-23 16:34 UTC, And-Martins commented on CustomerRegister/Controllers/CustomerController.cs
> +            }
Feito

2022-11-24 13:00 UTC, ghost commented on CustomerRegister/CustomerValidations.cs
> +        bool IsValidCpf(string cpf)
```suggestion
        private static bool IsValidCpf(string cpf)
```

2022-11-24 13:02 UTC, viniciusoliveira-warren commented on CustomerRegister/Services/CustomerService.cs
> +                throw new ArgumentException("Este CPF já está em uso, por favor escolha outro");
Se tentar fazer update de apenas um dos campos vai acabar estourando exceção, tem que adicionar validação de Id ser diferente do Id da entidade que estamos verificando que já existe

2022-11-24 13:03 UTC, viniciusoliveira-warren commented on CustomerRegister/Services/Interfaces/ICustomerService.cs
> +    }
```suggestion
        void Delete(int id);
    }
```

2022-11-24 13:13 UTC, And-Martins commented on CustomerRegister/Services/CustomerService.cs
> +                throw new ArgumentException("Este CPF já está em uso, por favor escolha outro");
Validação de id adicionada

2022-11-24 20:51 UTC, viniciusoliveira-warren commented on CustomerRegister/Services/CustomerService.cs
> +        }
Este método não está sendo usado, podemos remover

2022-11-24 20:52 UTC, viniciusoliveira-warren approved these changes

2022-11-25 16:21 UTC, And-Martins commented on CustomerRegister/Services/CustomerService.cs
> +        }
Feito

2022-11-25 16:21 UTC, merged