Ev 969 dotnet 02 aprofundamento c shap e net core
And-Martins/accelerate-everest-dotnet-api pull request #2
Opened 2022-11-24 18:08 UTC by And-Martins

- [x] Aplicação da Onion Architecture
- [x] Criação do AppServices
- [x] Criação do DomainModels
- [x] Criação do DomainServices
- [x] Aplicação do conceito de responsabilidade única

2022-11-25 17:23 UTC, santosclaudinei-warren commented on AppServices/AppServices.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```
Remover e fazer os imports de forma explicita através dos usings.

2022-11-25 17:24 UTC, santosclaudinei-warren commented on AppServices/Services/CustomerAppService.cs
> +       private readonly ICustomerAppService _customerAppService;
```suggestion
       private readonly ICustomerAppService _customerAppService;
       
```

2022-11-25 17:25 UTC, santosclaudinei-warren commented on AppServices/Services/CustomerAppService.cs
> +    internal class CustomerAppService : ICustomerAppService
```suggestion
    public class CustomerAppService : ICustomerAppService
```

2022-11-25 17:27 UTC, santosclaudinei-warren commented on AppServices/Services/CustomerAppService.cs
> +            _customerAppService.Update(customer);
```suggestion
            return _customerAppService.Update(customer);
```

2022-11-25 17:40 UTC, santosclaudinei-warren commented on AppServices/Services/ICustomerAppService.cs
> +using System.Threading.Tasks;
```suggestion
```
Não estão sendo utilizados

2022-11-25 17:44 UTC, santosclaudinei-warren commented on CustomerRegister/Controller/CustomerController.cs
> +using System;
```suggestion
```
estão sendo usados?

2022-11-28 12:13 UTC, And-Martins commented on AppServices/Services/CustomerAppService.cs
> +       private readonly ICustomerAppService _customerAppService;
Feito

2022-11-28 12:20 UTC, And-Martins commented on AppServices/Services/CustomerAppService.cs
> +            _customerAppService.Update(customer);
Esse método não retorna nada, por isso não tem o return

2022-11-28 12:21 UTC, gregoryzimmerwarren requested changes
Deixei alguns comentários.

Qualquer dúvida estou a disposição.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/AppServices.csproj
> +    <PackageReference Include="FluentValidation" Version="11.2.0" />
```suggestion
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.0" />
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        public int Add(CustomerEntity customer)
```suggestion
        public long Add(CustomerEntity customer)
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        public int Add(CustomerEntity customer)
O id é um long.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        public void Delete(int id)
```suggestion
        public void Delete(long id)
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        public CustomerEntity GetCustomerById(int id)
```suggestion
        public CustomerEntity GetCustomerById(long id)
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +            _customerAppService.Update(customer);
O Update dele é um void, não precisa colocar o return dai.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/Services/ICustomerAppService.cs
> +        CustomerEntity GetCustomerById(int id);
```suggestion
        CustomerEntity GetCustomerById(long id);
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/Services/ICustomerAppService.cs
> +        void Delete(int id);
```suggestion
        void Delete(long id);
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/Validators/CustomerValidations.cs
> +                Must(IsValidCpf).WithMessage("Por favor insira um CPF válido, este CPF está incorreto");
Eu mudaria a mensagem para: "CPF incorreto. Por favor insira um CPF válido no formato 000.000.000-00". Porque dai você tenta dar uma direção ao usuário de como deve ser a formatação ao menos, apesar de que quando o erro for em estar com um CPF inválido, por exemplo 111.111.111-11 não tem muito como explicar mesmo, além de dizer que tá invalido.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on AppServices/Validators/CustomerValidations.cs
> +                NotEmpty();
Tu precisa garantir que só maiores de 18 anos possam se cadastrar.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on CustomerRegister/Controller/CustomerController.cs
> +        }
```suggestion
        private readonly ICustomerAppService _customerAppService;

        public CustomerController(ICustomerAppService appService)
        {
            _customerappService = appService ?? throw new ArgumentNullException(nameof(customer));
        }
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on CustomerRegister/Controller/CustomerController.cs
> +        }
Tens que rever em toda a controller. Agora com a Onion Architecture tu tem mais essa camada intermediária de App, então agora teu caminho é:
Controller -> AppService -> DomainService

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on CustomerRegister/Controller/CustomerController.cs
> +                var exMessage = ex.InnerException?.Message ?? ex.Message;
Aplica isso em todas os teus catchs.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on CustomerRegister/Controller/CustomerController.cs
> +        public IActionResult GetCustomerById(int id)
```suggestion
        public IActionResult GetCustomerById(long id)
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on CustomerRegister/Controller/CustomerController.cs
> +        public ActionResult Delete(int id)
```suggestion
        public ActionResult Delete(long id)
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +var builder = WebApplication.CreateBuilder(args);
```suggestion
var builder = WebApplication.CreateBuilder(args);
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on CustomerRegister/Program.cs
> +builder.Services.AddScoped<IValidator<CustomerEntity>, CustomerValidations>();
Precisa inserir mais uma injeção de dependência referente ao AppService.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainModels/DomainModels.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainModels/DomainModels.csproj
> +    <Nullable>enable</Nullable>
Da uma conferida nos teus usings e nulidades para ver se não falta nada.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/DomainServices.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/DomainServices.csproj
> +    <Nullable>enable</Nullable>
Da uma olhada nos teus usings e nulidades para ver se não falta nada.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +                throw new ArgumentException("Este email já está em uso, por favor escolha outro");
```suggestion
                throw new ArgumentException($"Este email: {selectedCustomer.Email} já está em uso, por favor escolha outro");
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +                throw new ArgumentException("Este CPF já está em uso, por favor escolha outro");
```suggestion
                throw new ArgumentException($"Este CPF: {selectedCustomer.Cpf} já está em uso, por favor escolha outro");
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +                throw new ArgumentException("Este email já está em uso, por favor escolha outro");
Apenas para deixar mais claro para o usuário.

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +        public void Delete(int id)
```suggestion
        public void Delete(long id)
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainModels/Entities/CustomerEntity.cs
> +    public int Id { get; set; }
```suggestion
    public long Id { get; set; }
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainModels/Entities/IEntity.cs
> +        int Id { get; set; }
```suggestion
        long Id { get; set; }
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +        public CustomerEntity GetCustomerById(int id)
```suggestion
        public CustomerEntity GetCustomerById(long id)
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/Services/ICustomerService.cs
> +        CustomerEntity GetCustomerById(int id);
```suggestion
        CustomerEntity GetCustomerById(long id);
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/Services/ICustomerService.cs
> +        int Add(CustomerEntity customer);
```suggestion
        long Add(CustomerEntity customer);
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/Services/ICustomerService.cs
> +        void Delete(int id);
```suggestion
        void Delete(long id);
```

2022-11-28 12:21 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +        public int Add(CustomerEntity customer)
```suggestion
        public long Add(CustomerEntity customer)
```

2022-11-28 12:21 UTC, And-Martins commented on AppServices/Services/ICustomerAppService.cs
> +using System.Threading.Tasks;
Deletados

2022-11-28 12:24 UTC, And-Martins commented on CustomerRegister/Controller/CustomerController.cs
> +using System;
Sim, deletando essas importações ocorrem erros:

![image](https://user-images.githubusercontent.com/113135447/204277129-d7ffbaa6-e029-41e6-8ca5-9a0e45d9f6b7.png)

2022-11-28 13:04 UTC, AndreMartinsWarren commented on AppServices/Validators/CustomerValidations.cs
> +                Must(IsValidCpf).WithMessage("Por favor insira um CPF válido, este CPF está incorreto");
Realmente, dá uma sugestão de como resolver o problema, vou pensar assim nas próximas mensagens de exceção. Já mudei o texto para "O CPF inserido está incorreto. Por favor, insira um CPF válido no formato 000.000.000-00"

2022-11-28 13:33 UTC, And-Martins commented on AppServices/AppServices.csproj
> +    <Nullable>enable</Nullable>
Feito

2022-11-28 13:35 UTC, And-Martins commented on CustomerRegister/Controller/CustomerController.cs
> +        public IActionResult GetCustomerById(int id)
Feito

2022-11-28 13:35 UTC, And-Martins commented on CustomerRegister/Controller/CustomerController.cs
> +        public ActionResult Delete(int id)
Feito

2022-11-28 13:43 UTC, AndreMartinsWarren commented on CustomerRegister/Controller/CustomerController.cs
> +using System;
Conforme conversado, posso manter esses imports

2022-11-28 13:59 UTC, And-Martins commented on AppServices/Validators/CustomerValidations.cs
> +                NotEmpty();
Feito

2022-11-28 18:01 UTC, AndreMartinsWarren commented on CustomerRegister/Program.cs
> +builder.Services.AddScoped<IValidator<CustomerEntity>, CustomerValidations>();
feito

2022-11-28 18:09 UTC, And-Martins commented on DomainServices/Services/CustomerService.cs
> +        public void Delete(int id)
Feito

2022-11-28 18:10 UTC, And-Martins commented on DomainModels/Entities/CustomerEntity.cs
> +    public int Id { get; set; }
Feito

2022-11-28 18:10 UTC, And-Martins commented on DomainModels/Entities/IEntity.cs
> +        int Id { get; set; }
Feito

2022-11-28 18:14 UTC, And-Martins commented on CustomerRegister/Controller/CustomerController.cs
> +                var exMessage = ex.InnerException?.Message ?? ex.Message;
Feito

2022-11-28 18:16 UTC, And-Martins commented on DomainModels/DomainModels.csproj
> +    <Nullable>enable</Nullable>
Feito

2022-11-28 18:18 UTC, And-Martins commented on DomainServices/DomainServices.csproj
> +    <Nullable>enable</Nullable>
feito

2022-11-28 18:55 UTC, gregoryzimmerwarren approved these changes
Deixei só mais um comentário.

2022-11-28 18:55 UTC, gregoryzimmerwarren commented on CustomerRegister/Controller/CustomerController.cs
> +        }
```suggestion
        [HttpPost]
        public IActionResult Create(CustomerEntity customer)
        {
            try
            {
                var customerId = _customerAppService.Add(customer);
                return Created("Id: ", customerId);
            }
            catch (ArgumentException ex)
            {
                var exMessage = ex.InnerException?.Message ?? ex.Message;
                return BadRequest(exMessage);
            }
        }

        [HttpGet]
        public IActionResult GetAllCustomers()
        {
            try
            {
                var listCustomers = _customerAppService.GetAllCustomers();
                return Ok(listCustomers);
            }
            catch (Exception ex)
            {
                var exMessage = ex.InnerException?.Message ?? ex.Message;
                return Problem(exMessage);
            }
        }

        [HttpGet("{id}")]
        public IActionResult GetCustomerById(long id)
        {
            try
            {
                return Ok(_customerAppService.GetCustomerById(id));
            }
            catch (ArgumentNullException ex)
            {
                var exMessage = ex.InnerException?.Message ?? ex.Message;
                return NotFound(exMessage);
            }
        }

        [HttpPut]
        public IActionResult UpdateCustomer(CustomerEntity selectedCustomer)
        {
            try
            {
                _customerAppService.Update(selectedCustomer);
                return Ok();
            }
            catch (ArgumentNullException e)
            {
                var eMessage = e.InnerException?.Message ?? e.Message;
                return NotFound(e.Message);
            }
            catch (ArgumentException ex)
            {
                var exMessage = ex.InnerException?.Message ?? ex.Message;
                return BadRequest(exMessage);
            }
        }

        [HttpDelete("{id}")]
        public ActionResult Delete(long id)
        {
            try
            {
                _customerAppService.Delete(id);
                return NoContent();
            }
            catch (ArgumentNullException ex)
            {
                var exMessage = ex.InnerException?.Message ?? ex.Message;
                return NotFound(exMessage);
            }
        }
```

2022-11-29 16:18 UTC, santosclaudinei-warren approved these changes

2022-12-15 12:08 UTC, LuanFortunatoW approved these changes

2023-01-03 16:15 UTC, merged